create table processed_remote_files (
    id bigint generated by default as identity primary key,
    job_name varchar(150) not null,
    server_ref varchar(120) not null,
    remote_path varchar(1024) not null,
    filename varchar(255) not null,
    file_key varchar(512) not null,
    modified_time timestamp with time zone,
    size_bytes bigint not null,
    processed_at timestamp with time zone not null,
    status varchar(40) not null
);

create unique index ux_processed_remote_files_job_key
    on processed_remote_files (job_name, file_key);
